export const queryKey = {
  // POINTSLIST: 'pointsList',
  // REVIEWSME: 'reviewList',
  // HOMEDATA: 'homeData',
  // HOMEMISSION: 'homeMission',
  // ADDRESS: 'address',
  // MISSIONSPROGRESS: 'missionsProgress',
  // MISSIONSCOMPLETE: 'missionsComplete',
  USERINFO: 'userInfo',
  STOREINFO: 'storeInfo',
  STOREID: 'storeId',
  // STORELIST: 'storeList',
  // STOREDATA: 'storeData',
  // STOREREVIEWIMAGES: 'storeReviewImages',
  STOREIMAGES: 'storeImages',
  MENUIMAGES: 'menuImages',
  OPERATIONTIME: 'operationTime',
  STOREREVIEWLIST: 'storeReviewList',
  NOTIFICATIONS: 'notifications',
  NOTIFICATIONS_SETTING: 'notificationsSetting',
  QUESTIONS: 'questions',
  QUESTIONDETAIL: 'questionDetail',
  MISSIONSPROGRESS: 'missionsProgress',
  MISSIONSSUCCESS: 'missionsSuccess',
  MISSIONMANAGE: 'missionManage',
  MISSIONMANAGEDETAIL: 'missionManageDetail',
  STORERATING: 'storeRating',
  EYEBALLS: 'eyeballs',
};
